version: '3.9'

services:
  db:
    image: postgres:15               # oder eine feste Version wie „postgres:15“
    environment:
      POSTGRES_USER: admTim
      POSTGRES_PASSWORD: Freaks470.
      POSTGRES_DB: trading_signal
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
